name: Prepare

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - develop

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  prepare:
    uses: SP-Packages/actions/.github/workflows/code-quality.yml@v1.1.2
    with:
      VERBOSE: true
