name: Prepare

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - develop

jobs:
  prepare:
    uses: SP-Packages/actions/.github/workflows/code-quality.yml@main
    with:
      VERBOSE: true
