name: Release

on:
  push:
    branches:
      - main

jobs:
  prepare:
    uses: SP-Packages/actions/.github/workflows/code-quality.yml@main
    with:
      VERBOSE: true

  release:
    needs: prepare
    uses: SP-Packages/actions/.github/workflows/semantic-release.yml@main
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    with:
      RUN_BUILD: false
    permissions:
      contents: write
      issues: write
      pull-requests: write

  rebase:
    needs: release
    uses: SP-Packages/actions/.github/workflows/rebase-develop.yml@main
    permissions:
      contents: write
